baseurl = "http://127.0.0.1:4679/"
languageCode = "zh-CN"
theme = "demons-ladder"
title = "Nothing Here"
disqusShortname = "4679"
dateFormat = "%b %d, %Y"

subtitle = "Hi."
github = "https://github.com/4679"
weibo = "http://weibo.com/u/1963942417"
links = "https://libnull.com/friends/"
about = "https://libnull.com/about/"
profile = "https://dn-4679kun.qbox.me/head.jpg"
copyright = "Written by 4679kun"
analytics = "UA-32121582-2"
